### ISSUE TITLE
Observation API

### ISSUE THREAD

**Issue by tomaszmrugalski** [gut-space/satnogs#20]
We need a new API that will:

- [x] receive an observation from reporting ground station
- [x] rename uploaded file
- [x] store an observation in a DB
- [x] rename file using a scheme that ensures no conflicts
- [x] lastobs field in the stations table should be updated

It seems that over time more and more parameters will be provided when adding observation. The schema should be easily extensible. One good example would be a POST method with a JSON data and JSON response. This would also ensure easy adaptation by third parties.

**Comment by tomaszmrugalski** [comment]
One more thing - the lastobs field in the stations table should be updated.

**Comment by fivitti** [comment]
> receive an observation from reporting ground station

We have now API for receive the observations. It accept form-data or JSON formats. It required PNG file with observation and some metadata. After receiving server creates thumbnail.

> rename uploaded file
> rename file using a scheme that ensures no conflicts

Received file is renamed. We merge original filename with UUID (version 4). It allow us to avoid conflicts.
 
> store an observation in a DB

Received observation is inserted to existing DB shema.

**Comment by fivitti** [comment]
>  lastobs field in the stations table should be updated

Ready.

**Comment by tomaszmrugalski** [comment]
This seems to be complete. Resolving.
