### ISSUE TITLE
Experiment with LRPT reception and decoding

### ISSUE THREAD

**Issue by tomaszmrugalski** [gut-space/satnogs#33]
Right now we're only able to decode APT transmission, which is a 60s technology being used by only 3 NOAA sats and it is being retired. Newer sats (e.g. NOAA-20) no longer use APT. Our current hardware should allow us to receive [LRPT](https://en.wikipedia.org/wiki/Low-rate_picture_transmission) transmissions.

According to wikipedia, Metop and NPOESS use LRPT. [Metor 2-M](https://satsignal.eu/software/LRPT-processor.html) use LRPT, too. We should do some manual experiments and see how tricky it is to receive such transmissions.

**Comment by fivitti** [comment]
Decoding Meteor-M 2 with QPSK modulation is ready.

We receive signal on 137.1MHz and next demodulate it using [medet](https://github.com/dbdexter-dev/meteor_demod) and next retrieve imagery using [meteor-decoder](https://github.com/artlav/meteor_decoder). We compose RGB image from channels 68, 65 and 64 channels.

I notice that QPSK requires better signal than APT. If maximal elevation is less then 20 degrees then nothing is decoded.

**Comment by fivitti** [comment]
Next step: OQPSK modulation in Meteor-M2 2.

**Comment by fivitti** [comment]
137MHz LRPT transmission is no longer available.
I stop works on METEOR-M2 2 recipe.

I keep the ready recipe in MR #50 . 

[Source](https://www.rtl-sdr.com/meteor-m-n2-2-weather-satellite-updates-no-more-137-mhz-lrpt-l-x-band-working-in-daylight/)
